import type { Locale } from "@/lib/i18n/locale";

interface FactPart {
  text: string;
  bold?: boolean;
}

interface FaqItem {
  question: string;
  answer: string;
}

interface RelatedToolCard {
  name: string;
  description: string;
}

export interface QrCodeGeneratorPageContent {
  /** <title> and <meta description> */
  title: string;
  metaDescription: string;
  keywords: string[];
  ogTitle: string;
  ogDescription: string;
  /** Short base title the Twitter card title is built from: `${twitterTitle} — ${SITE_CONFIG.name}` */
  twitterTitle: string;
  twitterDescription: string;
  /** JSON-LD name/description/keywords */
  schemaName: string;
  schemaDescription: string;
  schemaKeywords: string[];
  h1: string;
  intro: string;
  whatIsHeading: string;
  whatIsParagraph: string;
  quickFactsHeading: string;
  quickFacts: FactPart[][];
  faqHeading: string;
  faq: FaqItem[];
  relatedToolsHeading: string;
  relatedToolsIntro: string;
  relatedTools: {
    base64: RelatedToolCard;
    colorPicker: RelatedToolCard;
  };
}

export const pageContent: Record<Locale, QrCodeGeneratorPageContent> = {
  en: {
    title: "QR Code Generator - Free Custom QR Codes with Logo & Colors",
    metaDescription:
      "Generate custom QR codes for free with colors, logos, and error correction. Create QR codes for URLs, WiFi, vCards, email, SMS, and text. Download as PNG or SVG instantly.",
    keywords: [
      "qr code generator",
      "free qr code",
      "custom qr code",
      "qr code maker",
      "qr generator",
      "url qr code",
      "wifi qr code",
      "vcard qr code",
      "qr code with logo",
      "colored qr code",
      "qr code download",
      "svg qr code",
      "png qr code",
      "qr code online",
      "business card qr",
    ],
    ogTitle: "QR Code Generator — Create Custom QR Codes with Logo & Colors",
    ogDescription:
      "Free QR code generator for URLs, WiFi, vCards, email, and SMS. Customize with colors and logos, adjust error correction, download as PNG/SVG.",
    twitterTitle: "QR Code Generator",
    twitterDescription:
      "Generate custom QR codes with logos and colors. Support for URLs, WiFi, vCards. Download PNG/SVG. Free tool.",
    schemaName: "QR Code Generator",
    schemaDescription:
      "Generate custom QR codes with colors, logos, and error correction for URLs, WiFi, vCards, email, and SMS",
    schemaKeywords: [
      "qr code generator",
      "custom qr code",
      "qr code maker",
      "wifi qr code",
      "vcard qr code",
    ],
    h1: "QR Code Generator",
    intro:
      "Generate custom QR codes for URLs, text, contact cards (vCard), WiFi credentials, email, and SMS. Customize colors, add logos, adjust error correction, and download as PNG or SVG. All processing happens in your browser for complete privacy.",
    whatIsHeading: "What is a QR Code?",
    whatIsParagraph:
      "A QR Code (Quick Response Code) is a two-dimensional barcode that stores information—like URLs, contact details, or WiFi credentials—in a pattern of black and white squares. Unlike traditional barcodes, QR codes hold data in both directions, letting them pack thousands of characters into a small space. Built-in error correction means a code can still scan correctly even if part of it is damaged or covered, and modern smartphones decode them instantly with the default camera app.",
    quickFactsHeading: "Quick Facts",
    quickFacts: [
      [
        { text: "Types:", bold: true },
        {
          text: " generate codes for URLs, plain text, vCard contacts, WiFi credentials, email, or SMS.",
        },
      ],
      [
        { text: "Common uses:", bold: true },
        {
          text: " marketing materials, business cards, product packaging, restaurant menus, event tickets, and payments.",
        },
      ],
      [
        { text: "Customization:", bold: true },
        {
          text: " add brand colors and a logo (up to ~30% of the code area) while keeping strong contrast.",
        },
      ],
      [
        { text: "Error correction:", bold: true },
        {
          text: " choose L/M/Q/H depending on damage risk—use the higher Q or H levels when embedding a logo.",
        },
      ],
      [
        { text: "Best practices:", bold: true },
        {
          text: " keep a quiet white border around the code, test scans on real devices before printing, and use SVG for large prints or PNG for screens.",
        },
      ],
      [
        { text: "Privacy:", bold: true },
        {
          text: " everything is generated locally in your browser—no data is ever sent to a server.",
        },
      ],
    ],
    faqHeading: "Frequently Asked Questions",
    faq: [
      {
        question:
          "Are QR codes generated by this tool free to use commercially?",
        answer:
          "Yes, all QR codes are free for personal and commercial use with no restrictions—QR code technology is an open standard that no one owns.",
      },
      {
        question: "Is my data safe using this QR code generator?",
        answer:
          "Yes. Every QR code is generated entirely in your browser—nothing is sent to our servers or any third party.",
      },
      {
        question: "Do QR codes expire or stop working?",
        answer:
          "Static QR codes like these never expire—the information is encoded directly in the pattern. If a code links to a URL, though, that destination still needs to stay online.",
      },
      {
        question: "Why isn't my QR code scanning properly?",
        answer:
          "Usually it's low contrast, a code that's too small, missing quiet space around the edges, or low-quality printing—check these first and re-test on a real device.",
      },
    ],
    relatedToolsHeading: "Related Tools",
    relatedToolsIntro: "Enhance your QR code workflow with these related tools:",
    relatedTools: {
      base64: {
        name: "Base64 Encoder",
        description: "Encode data for embedding in QR codes",
      },
      colorPicker: {
        name: "Color Picker",
        description: "Choose perfect colors for your custom QR codes",
      },
    },
  },
  de: {
    title: "QR-Code-Generator - Kostenlose individuelle QR-Codes mit Logo & Farben",
    metaDescription:
      "Erstelle kostenlos individuelle QR-Codes mit Farben, Logos und Fehlerkorrektur. QR-Codes für URLs, WLAN, vCards, E-Mail und SMS erzeugen. Sofort als PNG oder SVG herunterladen.",
    keywords: [
      "qr-code-generator",
      "kostenloser qr-code",
      "individueller qr-code",
      "qr-code erstellen",
      "qr-generator",
      "url-qr-code",
      "wlan-qr-code",
      "vcard-qr-code",
      "qr-code mit logo",
      "farbiger qr-code",
      "qr-code herunterladen",
      "svg-qr-code",
      "png-qr-code",
      "qr-code online",
      "visitenkarte qr",
    ],
    ogTitle:
      "QR-Code-Generator — Individuelle QR-Codes mit Logo & Farben erstellen",
    ogDescription:
      "Kostenloser QR-Code-Generator für URLs, WLAN, vCards, E-Mail und SMS. Mit Farben und Logos anpassen, Fehlerkorrektur einstellen, als PNG/SVG herunterladen.",
    twitterTitle: "QR-Code-Generator",
    twitterDescription:
      "Individuelle QR-Codes mit Logos und Farben erzeugen. Unterstützung für URLs, WLAN und vCards. PNG/SVG-Download. Kostenloses Tool.",
    schemaName: "QR-Code-Generator",
    schemaDescription:
      "Individuelle QR-Codes mit Farben, Logos und Fehlerkorrektur für URLs, WLAN, vCards, E-Mail und SMS erstellen",
    schemaKeywords: [
      "qr-code-generator",
      "individueller qr-code",
      "qr-code erstellen",
      "wlan-qr-code",
      "vcard-qr-code",
    ],
    h1: "QR-Code-Generator",
    intro:
      "Erstelle individuelle QR-Codes für URLs, Text, Kontaktkarten (vCard), WLAN-Zugangsdaten, E-Mail und SMS. Passe Farben an, füge ein Logo hinzu, stelle die Fehlerkorrektur ein und lade das Ergebnis als PNG oder SVG herunter. Die gesamte Verarbeitung läuft in deinem Browser ab – für vollständige Privatsphäre.",
    whatIsHeading: "Was ist ein QR-Code?",
    whatIsParagraph:
      "Ein QR-Code (Quick Response Code) ist ein zweidimensionaler Barcode, der Informationen – etwa URLs, Kontaktdaten oder WLAN-Zugangsdaten – in einem Muster aus schwarzen und weißen Quadraten speichert. Anders als klassische Barcodes speichern QR-Codes Daten in beide Richtungen und können so Tausende Zeichen auf kleinstem Raum unterbringen. Eine eingebaute Fehlerkorrektur sorgt dafür, dass ein Code auch dann noch korrekt gescannt werden kann, wenn ein Teil davon beschädigt oder verdeckt ist, und moderne Smartphones dekodieren ihn sofort mit der Standard-Kamera-App.",
    quickFactsHeading: "Schnellübersicht",
    quickFacts: [
      [
        { text: "Typen:", bold: true },
        {
          text: " Codes für URLs, reinen Text, vCard-Kontakte, WLAN-Zugangsdaten, E-Mail oder SMS erzeugen.",
        },
      ],
      [
        { text: "Typische Anwendungen:", bold: true },
        {
          text: " Marketingmaterialien, Visitenkarten, Produktverpackungen, Restaurant-Menüs, Eventtickets und Zahlungen.",
        },
      ],
      [
        { text: "Anpassung:", bold: true },
        {
          text: " Markenfarben und ein Logo hinzufügen (bis zu ca. 30 % der Codefläche), dabei auf starken Kontrast achten.",
        },
      ],
      [
        { text: "Fehlerkorrektur:", bold: true },
        {
          text: " L/M/Q/H je nach Beschädigungsrisiko wählen – bei eingebettetem Logo die höheren Stufen Q oder H verwenden.",
        },
      ],
      [
        { text: "Best Practices:", bold: true },
        {
          text: " einen ruhigen weißen Rand um den Code lassen, Scans vor dem Druck auf echten Geräten testen und SVG für große Drucke bzw. PNG für Bildschirme verwenden.",
        },
      ],
      [
        { text: "Datenschutz:", bold: true },
        {
          text: " alles wird lokal in deinem Browser erzeugt – es werden niemals Daten an einen Server gesendet.",
        },
      ],
    ],
    faqHeading: "Häufig gestellte Fragen",
    faq: [
      {
        question:
          "Sind die mit diesem Tool erzeugten QR-Codes kostenlos für die kommerzielle Nutzung?",
        answer:
          "Ja, alle QR-Codes sind für private und kommerzielle Nutzung ohne Einschränkungen kostenlos – die QR-Code-Technologie ist ein offener Standard, der niemandem gehört.",
      },
      {
        question: "Sind meine Daten bei der Nutzung dieses QR-Code-Generators sicher?",
        answer:
          "Ja. Jeder QR-Code wird vollständig in deinem Browser erzeugt – es wird nichts an unsere Server oder Dritte gesendet.",
      },
      {
        question: "Laufen QR-Codes ab oder hören sie irgendwann auf zu funktionieren?",
        answer:
          "Statische QR-Codes wie diese laufen nie ab – die Informationen sind direkt im Muster kodiert. Verweist ein Code jedoch auf eine URL, muss dieses Ziel trotzdem online bleiben.",
      },
      {
        question: "Warum lässt sich mein QR-Code nicht richtig scannen?",
        answer:
          "Meist liegt es an zu geringem Kontrast, einem zu kleinen Code, fehlendem Rand entlang der Kanten oder schlechter Druckqualität – das zuerst prüfen und dann erneut auf einem echten Gerät testen.",
      },
    ],
    relatedToolsHeading: "Verwandte Tools",
    relatedToolsIntro:
      "Ergänze deinen QR-Code-Workflow mit diesen verwandten Tools:",
    relatedTools: {
      base64: {
        name: "Base64-Encoder",
        description: "Daten zur Einbettung in QR-Codes kodieren",
      },
      colorPicker: {
        name: "Farbwähler",
        description: "Die perfekten Farben für deine individuellen QR-Codes auswählen",
      },
    },
  },
};
