import React from "react";

export function FAQSection() {
  return (
    <section>
      <h2 className="mb-4 text-xl font-bold text-gray-900 dark:text-gray-50 sm:mb-6 sm:text-3xl">
        Frequently Asked Questions
      </h2>
      <div className="space-y-4 sm:space-y-6">
        <details className="group rounded-xl border border-gray-200 bg-white p-4 dark:border-gray-800 dark:bg-gray-900 sm:p-6">
          <summary className="cursor-pointer text-base font-semibold text-gray-900 dark:text-gray-50 sm:text-lg">
            Are QR codes generated by this tool free to use commercially?
          </summary>
          <p className="mt-2 text-sm text-gray-700 dark:text-gray-300 sm:mt-3 sm:text-base">
            Yes, all QR codes are free for personal and commercial use with
            no restrictions—QR code technology is an open standard that no
            one owns.
          </p>
        </details>

        <details className="group rounded-xl border border-gray-200 bg-white p-4 dark:border-gray-800 dark:bg-gray-900 sm:p-6">
          <summary className="cursor-pointer text-base font-semibold text-gray-900 dark:text-gray-50 sm:text-lg">
            Is my data safe using this QR code generator?
          </summary>
          <p className="mt-2 text-sm text-gray-700 dark:text-gray-300 sm:mt-3 sm:text-base">
            Yes. Every QR code is generated entirely in your browser—nothing
            is sent to our servers or any third party.
          </p>
        </details>

        <details className="group rounded-xl border border-gray-200 bg-white p-4 dark:border-gray-800 dark:bg-gray-900 sm:p-6">
          <summary className="cursor-pointer text-base font-semibold text-gray-900 dark:text-gray-50 sm:text-lg">
            Do QR codes expire or stop working?
          </summary>
          <p className="mt-2 text-sm text-gray-700 dark:text-gray-300 sm:mt-3 sm:text-base">
            Static QR codes like these never expire—the information is
            encoded directly in the pattern. If a code links to a URL,
            though, that destination still needs to stay online.
          </p>
        </details>

        <details className="group rounded-xl border border-gray-200 bg-white p-4 dark:border-gray-800 dark:bg-gray-900 sm:p-6">
          <summary className="cursor-pointer text-base font-semibold text-gray-900 dark:text-gray-50 sm:text-lg">
            Why isn&apos;t my QR code scanning properly?
          </summary>
          <p className="mt-2 text-sm text-gray-700 dark:text-gray-300 sm:mt-3 sm:text-base">
            Usually it&apos;s low contrast, a code that&apos;s too small, missing
            quiet space around the edges, or low-quality printing—check
            these first and re-test on a real device.
          </p>
        </details>
      </div>
    </section>
  );
}
